### ISSUE TITLE
Set a @cache for reward calculation 

### ISSUE THREAD

**Issue by carlocagnetta** [appliedAI-Initiative/armscan_env#12]
So that the reward is not calculated multiple times for the observations, it is best to set a @cache call.
The idea is to use `@lru_cache(max_size=100)`.
This means, that the parameters of the function `anatomy_based_rwd` shall be hashable.
Its parameters are `tissue_clusters` and `n_landmarks`.

PArameter `tissue_clusters` is a dataclass `TissuClusters` which consists as well of the dataclass elements `DataCluster`. In this two dataclasses, the `__hash__` method needs to be implemented.

**Comment by carlocagnetta** [comment]
@MischaPanch Do you realistically have time to do this soon, to improve the speed of results?

**Comment by MischaPanch** [comment]
I'll look at it today, sry for the delay. Forgot about this in the midst of the recent turmoils ^^
